/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class InsertDataintoUserRequest implements Serializable {


    @JsonProperty("USERNAME")
    @NotNull
    private String username;

    @JsonProperty("PASSWORD")
    @NotNull
    private String password;

    @JsonProperty("ROLE")
    @NotNull
    private String role;

    @JsonProperty("TENANT_ID")
    @NotNull
    private String tenantId;

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof InsertDataintoUserRequest)) return false;
        final InsertDataintoUserRequest insertDataintoUserRequest = (InsertDataintoUserRequest) o;
        return Objects.equals(getUsername(), insertDataintoUserRequest.getUsername()) &&
                Objects.equals(getPassword(), insertDataintoUserRequest.getPassword()) &&
                Objects.equals(getRole(), insertDataintoUserRequest.getRole()) &&
                Objects.equals(getTenantId(), insertDataintoUserRequest.getTenantId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getUsername(),
                getPassword(),
                getRole(),
                getTenantId());
    }
}
